import jsPDF from "jspdf";
import html2pdf from "html2pdf.js";

/**
 * Export document content to PDF file
 * @param filename - Name of the PDF file (without .pdf extension)
 * @param title - Document title
 * @param content - Main content to export
 * @param metadata - Additional info (reference number, BAN, status, etc.)
 */
export const exportDocumentToPDF = (
  filename: string,
  title: string,
  content: string,
  metadata?: {
    referenceNumber?: string;
    ban?: string;
    status?: string;
    createdAt?: string;
  }
) => {
  // Create HTML element with styled content
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${title}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
          margin: 0;
          padding: 20px;
        }
        .header {
          border-bottom: 2px solid #0066cc;
          padding-bottom: 15px;
          margin-bottom: 20px;
        }
        .header h1 {
          margin: 0 0 10px 0;
          font-size: 24px;
          color: #0066cc;
        }
        .metadata {
          background: #f5f5f5;
          padding: 12px;
          border-radius: 5px;
          margin-bottom: 20px;
          font-size: 12px;
        }
        .metadata-row {
          display: flex;
          justify-content: space-between;
          margin-bottom: 5px;
        }
        .metadata-label {
          font-weight: bold;
          color: #666;
          min-width: 100px;
        }
        .content {
          white-space: pre-wrap;
          word-wrap: break-word;
          margin-top: 20px;
          font-size: 12px;
        }
        .markdown-content {
          margin-top: 20px;
          font-size: 13px;
        }
        .markdown-content h1, .markdown-content h2, .markdown-content h3 {
          color: #0066cc;
          margin-top: 15px;
          margin-bottom: 10px;
        }
        .markdown-content ul, .markdown-content ol {
          margin-left: 20px;
        }
        .markdown-content li {
          margin-bottom: 5px;
        }
        .markdown-content p {
          margin: 10px 0;
        }
        .footer {
          margin-top: 30px;
          padding-top: 15px;
          border-top: 1px solid #ddd;
          font-size: 10px;
          color: #999;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${escaped(title)}</h1>
      </div>
      
      ${
        metadata
          ? `
      <div class="metadata">
        ${metadata.referenceNumber ? `<div class="metadata-row"><span class="metadata-label">Reference:</span><span>${escaped(metadata.referenceNumber)}</span></div>` : ""}
        ${metadata.ban ? `<div class="metadata-row"><span class="metadata-label">BAN:</span><span>${escaped(metadata.ban)}</span></div>` : ""}
        ${metadata.status ? `<div class="metadata-row"><span class="metadata-label">Status:</span><span>${escaped(metadata.status)}</span></div>` : ""}
        ${metadata.createdAt ? `<div class="metadata-row"><span class="metadata-label">Created:</span><span>${escaped(metadata.createdAt)}</span></div>` : ""}
      </div>
      `
          : ""
      }
      
      <div class="markdown-content">${content}</div>
      
      <div class="footer">
        <p>This document was generated by the NBA Anaocha Digital Portal</p>
        <p>Generated on ${new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" })}</p>
      </div>
    </body>
    </html>
  `;

  // Use html2pdf to convert and download
  const element = document.createElement("div");
  element.innerHTML = htmlContent;

  const options = {
    margin: 8,
    filename: `${filename}.pdf`,
    image: { type: "jpeg" as const, quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { orientation: "portrait" as const, unit: "mm", format: "a4" },
  };

  html2pdf().set(options).from(element).save();
};

// Helper function to escape HTML special characters
function escaped(text: string): string {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Export document for MyDocuments (full document preview)
 */
export const exportDocument = (doc: any) => {
  const filename = doc.reference_number || `document-${doc.id}`;
  const title = doc.title || "Legal Document";
  const status = doc.status === "completed" ? "Completed" : "Draft";

  exportDocumentToPDF(filename, title, doc.content || doc.form_data || "", {
    referenceNumber: doc.reference_number,
    ban: doc.ban,
    status,
    createdAt: doc.created_at
      ? new Date(doc.created_at).toLocaleDateString("en-NG", {
          day: "numeric",
          month: "short",
          year: "numeric",
        })
      : undefined,
  });
};
